---
title: "US Labor Market"
author: "Arisa Thongngam"
date: "2025-12-01"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("fredr")
install.packages(c("tidyr", "lubridate", "purrr"))
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(purrr)
#library(fredr)
```


```{r, include = FALSE}
#CPI data for calculating inflation rate
#Real GDP for GDP growth (%change) (data comes in Quartery so convert the frequency to monthly)
#Women LFPR
#Men LFPR
#Unemployment rate
#Consider lag 1 for last year effect on this year
#Include year as a covariate
#Population growth or mortality rate

```

```{r, include = FALSE}
getwd()
#Reading data
CPI <- read.csv("data/CPI.csv")
GDP <- read.csv("data/GDP.csv")
MLFPR <- read.csv("data/MLFPR.csv")
WLFPR <- read.csv("data/WLFPR.csv")
UNRATE <- read.csv("data/UNRATE.csv")

head(MLFPR)
tail(CPI)

#Renaming observations
CPI <- CPI %>%
  rename(CPI = CPILFESL)

GDP <- GDP %>%
  rename(GDP = GDPC1)

MLFPR <- MLFPR %>%
  rename(MLFPR = Value)

WLFPR <- WLFPR %>%
  rename(WLFPR = Value)

UNRATE <- UNRATE %>%
  rename(UNRATE = Value)


#Converting the class of date from character to date.time
GDP$observation_date <- as.Date(GDP$observation_date)
class(GDP$observation_date)
#Converting GDP from Quarterly to Monthly
GDP_M <- GDP %>%
  #Adding a "month_seq" column
  #For each quarterly date, return a vector of three monthly dates
  mutate(month_seq = map(observation_date, ~ seq(.x, by = "1 month", length.out = 3))) %>%
  unnest(month_seq) %>%
  #Delete original observation date column
  select(-observation_date) %>% 
  #Rename the month_aeq column to "observation_date"
  rename(observation_date = month_seq) %>%
  #Sorting observation_date in a chronological order
  arrange(observation_date)
head(GDP_M)

#Removing row 247-249 so that all variables have 246 observations
CPI <- CPI[-c(247:249), ]
MLFPR <- MLFPR[-c(247:249), ]
WLFPR <- WLFPR[-c(247:249), ]
UNRATE <- UNRATE[-c(247:249), ]

#Creating an observation_date column so that all data frames have a common column
CPI$observation_date <- as.Date(CPI$observation_date)
MLFPR$observation_date <- CPI$observation_date
WLFPR$observation_date <- CPI$observation_date
UNRATE$observation_date <- CPI$observation_date

#Merging by the "observation_date" column
df1 <- CPI %>%
  left_join(MLFPR %>% select(observation_date, MLFPR),
            by = "observation_date") %>%
  left_join(WLFPR %>% select(observation_date, WLFPR),
            by = "observation_date") %>%
  left_join(UNRATE %>% select(observation_date, UNRATE, Year),
            by = "observation_date") %>%
  left_join(GDP_M %>% select(observation_date, GDPC1),
            by = "observation_date")
  
head(df1)
```


```{r}
#Create an empty vector for inflation
INF_RATE <- numeric(nrow(df1))

#Loop to calculate inflation rate using percentage change in CPI
for (i in 2:nrow(df1)) {
  INF_RATE[i] <- ((df1$CPI[i] - df1$CPI[i-1]) / df1$CPI[i-1]) * 100
}

#Append to dataframe
df1$INF_RATE <- INF_RATE


#Creating GDP growth

head(df1)


```


```{r}
#Plotting each series
#Unemployment rate
UNRATE_g <- ggplot(data = df1,
                   mapping = aes(x = observation_date, 
                                 y = UNRATE)) +
  geom_line(linewidth = 0.8) +
  labs(x = "Year",
       y = "Unemployment Rate (%)",
       title = "U.S. Unemployment Rate (2005-2025)") +
  theme_bw()

#save the plot
ggsave(UNRATE_g, 
       filename = "UNRATE_g.png",
       device = "png")

#Men Labor Force Participation Rate
MLFPR_g <- ggplot(data = df1,
                   mapping = aes(x = observation_date, 
                                 y = MLFPR)) +
  geom_line(linewidth = 0.8) +
  labs(x = "Year",
       y = "Men Labor Force Participation Rate (%)",
       title = "Men Labor Force Participation Rate in the U.S. (2005-2025)") +
  theme_bw()

#save the plot
ggsave(MLFPR_g, 
       filename = "MLFPR_g.png",
       device = "png")

#Women Labor Force Participation Rate
WLFPR_g <- ggplot(data = df1,
                   mapping = aes(x = observation_date, 
                                 y = WLFPR)) +
  geom_line(linewidth = 0.8) +
  labs(x = "Year",
       y = "Women Labor Force Participation Rate (%)",
       title = "Women Labor Force Participation Rate in the U.S. (2005-2025)") +
  theme_bw()

#save the plot
ggsave(WLFPR_g, 
       filename = "WLFPR_g.png",
       device = "png")

#Monthly Inflation Rate
INFR_g <- ggplot(data = df1,
                   mapping = aes(x = observation_date, 
                                 y = INF_RATE)) +
  geom_line(linewidth = 0.8) +
  labs(x = "Year",
       y = "Inflation Rate (%)",
       title = "Inflation Rate in the U.S. (2005-2025)") +
  theme_bw()

#save the plot
ggsave(INFR_g, 
       filename = "INFR_g.png",
       device = "png")

#Real GDP
GDP_g <- ggplot(data = GDP,
                   mapping = aes(x = observation_date, 
                                 y = GDPC1)) +
  geom_line(linewidth = 0.8) +
  labs(x = "Year",
       y = "GDP",
       title = "U.S. Gross Domestic Product (2005-2025)") +
  theme_bw()

#save the plot
ggsave(GDP_g, 
       filename = "GDP_g.png",
       device = "png")





```


